#!/bin/sh

if [ $# != 1 ]; then
	echo "Usage: h3master HMMFILE" >&2
	exit 1
fi

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	echo "Usage: h3master HMMFILE" >&2
	exit 0
fi

if ! test -e "$1"; then
	echo "File <$1> not found." >&2
	exit 1
fi

/usr/local/bin/hmmpgmd --master --hmmdb "$1"
